[tools]
node      = "25"
ruby      = "3"
python    = "3"
ghq       = "latest"
crystal   = "1"
terraform = "latest"
rust      = "latest"
atuin = "latest"
go = "latest"
gh = "latest"
carapace = "latest"
jq = "latest"
eza = "latest"
bat = "latest"
direnv = "latest"
delta = "latest"
fd = "latest"
lazygit = "latest"
yq = "latest"
starship = "latest"
fzf = "latest"
yazi = "latest"
zoxide = "latest"
usql = "latest"
usage = "latest"
"npm:mcp-hub" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby", "node"]
experimental = true
